// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("activewindow")
	ScopeName = "github.com/rogercoll/activewindowreceiver"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
